### ISSUE TITLE
The hack no longer works.

### ISSUE THREAD

**Issue by JASFramework** [Elspex/skidfest#2]
So I still can get the hack to load in for a second but then Krunker lags like crazy and says "Bad Connection". 

As a note, it only says that when the hack is on. This was a great hack please make it work again!

Btw if you want to pass on what you are doing I would be happy to learn!

**Comment by Elspex** [comment]
Jaswafford1211,
I'm sorry you are having these problems. The hacks are down, but only for maintenance. They will be back up in a few days! If you have this problem again try redownloading tampermonkey and try again. As for the teaching part, i would love to help, alas i'm a horrible teacher. But i will keep making these hacks to help you destroy some sweats in krunker.io! 
Thanks!
- Elspex
